name: Release

on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  generate:
    name: Generate
    uses: cupel-co/workflows/.github/workflows/generate-version.yml
  
  release:
    name: Release
    uses: cupel-co/workflows/.github/workflows/github-release.yml
    needs:
      - generate
    permissions:
      contents: write
    with:
      tag: "v${{ needs.generate.outputs.sem-ver }}"
    secrets:
      gpg-key: "${{ secrets.GH_GPG_PRIVATE_KEY }}"
      gpg-password: "${{ secrets.GH_GPG_PRIVATE_KEY_PASSWORD }}"
      google-chat-webhook-url: "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"
