name: 'Release'

on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: false
  group: release-${{ github.ref_name }}

jobs:
  generate-version:
    name: Generate Version
    runs-on: ubuntu-latest
    outputs:
      sem-ver: ${{ steps.get-version.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
      - name: Get version
        id: get-version
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          targetPath: ./
          disableCache: true
          useConfigFile: true
          configFilePath: GitVersion.yml
        env:
          BUILD_NUMBER: ${{ github.run_number }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - generate-version
    env:
      tag: v${{ needs.generate-version.outputs.sem-ver }}
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GH_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GH_GPG_PRIVATE_KEY_PASSWORD }}
          git_user_signingkey: true
          git_tag_gpgsign: true
      - name: Create and push tag
        run: |
          git tag -s ${{ env.tag }} -m "${{ env.tag }}"
          git push origin tag ${{ env.tag }}
      - name: Generate changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ env.tag }}
          writeToFile: false
          includeInvalidCommits: true
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body: "${{ steps.changelog.outputs.changes }}"
          tag_name: ${{ env.tag }}
          make_latest: true
